// Generated by CanvasL Visual Compiler v1.1.0
// Canvas: examples/spatial-hello-world.json

console.log("Hello from CanvasL spatial programming!");
console.log("Nodes processed:", 4);
console.log("Edges processed:", 2);

// Your spatial program has been compiled successfully!
