#lang racket

;; Minimal Racket HTTP Server for Testing
(require web-server/servlet
         web-server/servlet-env
         web-server/http
         json)

;; Simple health endpoint
(define (health-endpoint request)
  (response/full
   200
   #"OK"
   (current-seconds)
   #"application/json"
   empty
   (list (jsexpr->bytes (hasheq 'status "healthy" 'timestamp (current-seconds))))))

;; Simple generate endpoint
(define (generate-endpoint request)
  (let* ([body (request-post-data/raw request)]
         [ast-data (if body (bytes->jsexpr body) (hasheq))])
    (response/full
     200
     #"OK"
     (current-seconds)
     #"application/json"
     (list (header #"Access-Control-Allow-Origin" #"*"))
     (list (jsexpr->bytes 
            (hasheq 'success #t
                   'code "#lang racket\n\n;; Generated by Logos\n(define (main)\n  (printf \"CanvasL Program~n\"))\n"
                   'metadata (hasheq 'lines 4 'language "racket")))))))

;; CORS endpoint
(define (cors-endpoint request)
  (response/full
   200
   #"OK"
   (current-seconds)
   #"text/plain"
   (list (header #"Access-Control-Allow-Origin" #"*")
         (header #"Access-Control-Allow-Methods" #"POST, OPTIONS")
         (header #"Access-Control-Allow-Headers" #"Content-Type"))
   #""))

;; Routes
(define-values (dispatch generate-url)
  (dispatch-rules
   [("") health-endpoint]
   [("health") health-endpoint]
   [("generate") #:method "post" generate-endpoint]
   [("generate") #:method "options" cors-endpoint]))

;; Start server
(serve/servlet dispatch
               #:port 8080
               #:listen-ip "127.0.0.1"
               #:servlet-path "/"
               #:servlet-regexp #rx""
               #:command-line? #t)