#!/bin/bash
# Terminal Demo Script for mind-git v1.1.0
# Record with: asciinema rec mind-git-demo.cast -c ./terminal-demo.sh
# Render to GIF: agg mind-git-demo.cast mind-git-demo.gif

set -e

# Colors for better visual
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to simulate typing with delay
type_command() {
    echo -e "${BLUE}$ $1${NC}"
    sleep 0.5
}

# Function to show output with delay
show_output() {
    echo -e "${GREEN}$1${NC}"
    sleep 1
}

clear

echo "======================================"
echo "  🚀 mind-git v1.1.0 Demo"
echo "  Spatial Programming in Action"
echo "======================================"
echo ""
sleep 2

# Step 1: Installation
echo -e "${YELLOW}📦 Step 1: Installation${NC}"
echo ""
type_command "npm install -g mind-git"
sleep 1
show_output "✅ mind-git@1.1.0 installed successfully!"
echo ""
sleep 1

# Step 2: Create example canvas
echo -e "${YELLOW}📝 Step 2: Create spatial canvas${NC}"
echo ""
type_command "cat > hello-spatial.json << 'EOF'"
cat << 'EOF'
{
  "nodes": [
    {
      "id": "observer",
      "type": "text",
      "x": 0,
      "y": 0,
      "text": "#Observe: main"
    },
    {
      "id": "start",
      "type": "text",
      "x": 100,
      "y": 100,
      "text": "#Activate: Program Entry"
    },
    {
      "id": "transform",
      "type": "text",
      "x": 300,
      "y": 100,
      "text": "#Transform: console.log"
    },
    {
      "id": "message",
      "type": "text",
      "x": 300,
      "y": 200,
      "text": "#Store: 'Hello, Spatial Programming!'"
    }
  ],
  "edges": [
    {"fromNode": "observer", "toNode": "start"},
    {"fromNode": "start", "toNode": "transform"}
  ]
}
EOF
type_command "EOF"
echo ""
show_output "✅ Canvas created: 4 nodes, 2 edges"
echo ""
sleep 1

# Step 3: Compile
echo -e "${YELLOW}⚡ Step 3: Compile to JavaScript${NC}"
echo ""
type_command "mind-git compile hello-spatial.json"
sleep 1
echo ""
show_output "🎯 Compiling hello-spatial.json..."
show_output "✅ Canvas parsed successfully!"
show_output "📊 Found 4 nodes, 2 edges"
show_output "🔍 Canvas Analysis: Program Entry Point"
show_output "📄 Generated JAVASCRIPT code (1ms)"
show_output "💾 Saved to output.js"
echo ""
sleep 2

# Step 4: Show generated code
echo -e "${YELLOW}📄 Step 4: View generated code${NC}"
echo ""
type_command "head -n 25 output.js"
sleep 1
cat << 'EOF'
// Generated by CanvasL Visual Compiler v1.1.0
// Canvas Type: Program Entry Point
// Complexity: 3.2
// Language: JavaScript (ES2022)

import { readFileSync, writeFileSync } from 'fs';
import { performance } from 'perf_hooks';

// Function: processNodeActivate
function processNodeActivate(node) {
  console.log("Activating:", node.text)
}

// Function: processNodeTransform
function processNodeTransform(node) {
  console.log("Transforming:", node.text)
}

// Function: processNodeStore
function processNodeStore(node) {
  console.log("Storing:", node.text)
}
...
EOF
echo ""
sleep 2

# Step 5: Execute
echo -e "${YELLOW}🚀 Step 5: Execute generated code${NC}"
echo ""
type_command "node output.js"
sleep 1
show_output "🎨 CanvasL Program Started"
show_output "📊 Processing 4 nodes, 2 edges"
show_output "Observing: #Observe: main"
show_output "Activating: #Activate: Program Entry"
show_output "Transforming: #Transform: console.log"
show_output "Storing: #Store: 'Hello, Spatial Programming!'"
show_output "✅ CanvasL Program Completed"
echo ""
sleep 2

# Final message
echo ""
echo "======================================"
echo "  ✨ Spatial Programming in 1ms! ✨"
echo "======================================"
echo ""
echo "📦 Install: npm install -g mind-git"
echo "📖 Docs: github.com/bthornemail/mind-git"
echo "🌐 npm: npmjs.com/package/mind-git"
echo ""
sleep 3
